### ISSUE TITLE
Request for  Extracted Rule Files

### ISSUE THREAD

**Issue by Bohemianc** [xiaxia-wang/FaithfulRE#1]
Hi Xiaxia,

Nice work!
If it's convenient, could you upload the files containing the extracted rules? Although you've provided the parameters for extracting the rules, retraining the model is quite time-consuming. It would be really helpful.

Thank you!

**Comment by xiaxia-wang** [comment]
Thanks for the question. 

Actually the model training time won't be very long (see the training time results in Appendix D). I would recommend training from scratch, so that it will be more flexible to control the rule extraction process by adjusting hyperparameters. And the codes for extracting rules are provided. On the other hand, the complete file of rules is relatively large (exceeds the single file size limitation of github). If you do want any of them, please let me know the dataset, model name, and all the setting of parameters.

**Comment by Bohemianc** [comment]
Thanks for your relpy. I would train the models from scratch as suggested. By the way, I would like to know how to extract rules from the DRUM model using your code. Could you provide a more detailed explanation?

**Comment by xiaxia-wang** [comment]
Please refer to the Algorithm 2 and Appendix C for details. Also, you may use the function extract_rule_explanation_drum to obtain explanation for a single fact.

**Comment by Bohemianc** [comment]
Thank you!
